apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-dvr-data-pvc
spec:
  storageClassName: ""
  volumeName: agent-dvr-data-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
