apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-r2
  namespace: juicefs
type: Opaque
stringData:
  name: "cloudflare-r2-prod"
  metaurl: ""
  storage: "s3"
  bucket: "https://4c8ad4e9fa8213af3fd284bb97b68b5e.r2.cloudflarestorage.com/juicefs-prod"
  accessKey: ""
  secretKey: ""
  # https://github.com/juicedata/juicefs/pull/4219/changes
  # https://github.com/juicedata/juicefs/issues/4206
  envs: '{"JFS_MOUNT_TIMEOUT": 300}'
