metallb:
  enabled: true
traefik:
  enabled: true
openebs:
  enabled: true
postgresql:
  enabled: true
mongodb:
  enabled: false
velero:
  enabled: true
kubePrometheusStack:
  enabled: true
mongoOperator:
  enabled: true
kafkaOperator:
  enabled: true
customManifest:
  enabled: true
