metallb:
  enabled: false
traefik:
  enabled: false
openebs:
  enabled: false
postgresql:
  enabled: false
velero:
  enabled: false
kubePrometheusStack:
  enabled: false
mongo:
  enabled: false
kafkaOperator:
  enabled: false
customManifest:
  enabled: false
loki:
  enabled: false
alloy:
  enabled: false
pgadmin4:
  enabled: false
harbor:
  enabled: false ## unstable
sonarqube:
  enabled: false
juicefs:
  enabled: false
vaultwarden:
  enabled: false
certManager:
  enabled: false
redis:
  enabled: false
nfsCsiDriver:
  enabled: false
qbittorrent:
  enabled: false
jellyfin:
  enabled: false
agentDvr:
  enabled: false
nextcloud:
  enabled: false
argus:
  enabled: false
crowdsec:
  enabled: false
chaosMesh:
  enabled: false
eck:
  enabled: false
teleport:
  enabled: false
