# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.secret.adminToken | quote }}
  DUO_SKEY: {{ .Values.secret.duoSkey | quote }}
  PUSH_INSTALLATION_ID: {{ .Values.secret.pushInstallationId | quote }}
  PUSH_INSTALLATION_KEY: {{ .Values.secret.pushInstallationKey | quote }}
  YUBICO_SECRET_KEY: {{ .Values.secret.yubicoSecretKey | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  SMTP_USERNAME: {{ .Values.secret.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secret.smtpPassword | quote }}