secret:
    ADMIN_TOKEN: ENC[AES256_GCM,data:bDHbBItix+YgPuxzVVIGftPZWA2EUgW30HhT+w/FziHjXIgJkYVO1ZkLCu09ZBt3E4wBAv9l7KZvZR7dFeoJzg==,iv:kXnvVA1BtO6QLI/hfzfl/pBy4/8oWnJ/T3ixVVncg6k=,tag:MaZfqGnN1G9vF6GivTCLKQ==,type:str]
    DUO_SKEY: ""
    PUSH_INSTALLATION_ID: ""
    PUSH_INSTALLATION_KEY: ""
    YUBICO_SECRET_KEY: ""
    DATABASE_URL: ENC[AES256_GCM,data:PGWpnwG0MDPLW/A+GqRXeGdaV3VNQ6g/T7S8Wcq6Nd8efvIJiNz7eHtUYfSftw3KMo4o3y1MBGMrlfZYyHxPusawPCxU/mbKqWUzUZiLY1EsgO5IfDNqUTmMf4apwjwrhA==,iv:cf9QB+57FsmC/i3HBmubpbUu2gRDQ9AbjizDx6DbpEQ=,tag:+55u65Oe9MTTHYuJdFUj6Q==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:mm5FH+R0mQ71C864KyQvkaVxEwCYzw==,iv:0S8BT9L30tu0jESE2gbmefGKucV/U7WZYeRzpYgAwGw=,tag:PddJr8EyxpKsPt4xXtdDqw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:7bdMNcRpss0APCTRBambsg==,iv:J1VxQPaX13sEJe2j7Xgch7uKWKnSDV0q/io67tgRR5E=,tag:nXj5ecbDrEq71GdQbPdgIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRklzek9CQlFNakM5akIw
            N1UwS0VvR1RtMWk0YkhXdEJMdU9RNFlLS3hNCmR0Y3Q0RmFtYkQvc2U3Nit1emVH
            M1BwNk44Y3FyZzQvZXV4N1pibjYvK2cKLS0tIGE3WWpGdzVtS3RDRVBlbmg5czEy
            UXIxR0ZJUHprNlFEdGlPTExiaUd3Vk0KQwTcuZdyAjSZ5LQQIS0c706Mlfe9xvdx
            tlVq8lMCQltWOrpLR1x8ESlWgX6OJ6gmTN7vNsNQDKBY9Ytu0ap98g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
    lastmodified: "2026-07-18T08:23:36Z"
    mac: ENC[AES256_GCM,data:lfOsNCziNFM5RIMRcVGwb4by1N1kp02TX+8KTmu5oKyoPgjdADoSYfkAKVd05Q4P8lpNMhLEiAwBiJ6AreW/wWVqhOsK2ViolDyC0flceyVcurOP6i1YQ18lkh3xDDqfIGYok2NuY8fPt/rdLffetPebWoEpK4mFB6m44ufZvcQ=,iv:JAapWfufDasjQfqXVynzT3WkWdtIHzS0uIO3vJBUoow=,tag:Y1OTFzSSVoLOcpKGCEp2lg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|name|namespace|labels|annotations)$
    version: 3.13.0
