smtp:
    username:
        value: ENC[AES256_GCM,data:4X+xnUtFIenIHO5dqIEFsq4yUvZtEw==,iv:TiW8zV36jzZx9KyBvTyW65AXAdpZBic0b30YxcFm2Ig=,tag:1Tg0tAfHY0uXSXwB+5TsVA==,type:str]
    password:
        value: ENC[AES256_GCM,data:ROsYW3B4ZOa3rTFpWQ2O5g==,iv:EUjGwoT5+8A02b8Q6WgiDqgnieDseJ3X/YLVMApV1Hk=,tag:LegL6+yB7tNvwtpMErve9A==,type:str]
adminToken:
    value: ENC[AES256_GCM,data:u6ZAnlqMmpCdm9GhLUJLTAaqgzEjFlSeGICJSHzk6sDKm2QIUtVM2O+bd6JScVl6fTKD5Er9KM1N0qnGpXVlVQ==,iv:t79MNXjvludbmTnd+905QVClLDfMTbNTYWUq9ky7LRc=,tag:HqTxhFEVKC2trQvlbypDVg==,type:str]
database:
    uriOverride: ENC[AES256_GCM,data:Rd4iWSjl1j94Oc/EymcFaY39+/e23510hVpmsY1TlyFQX5/VJxg/d/FgkMZS8TK7xYpWUKndlA2mE9+t1F5K/e06FDngbsnAtNsExrg3nFIPHsMVjrAgs6Yl6/VJngEqGA==,iv:On4HefxMXtZQpGiXFdxs6QbcEqwFc7CtsTZORMKYjkE=,tag:0DW4XpRy4o0UI8hdNLKWJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZkUzVXo4RlR2allhbkR0
            QWhLZmRpNTlyOHc5ajFFRnhpMVhtWmVyUjBvCjBUeG9zZ2puTmtzODBqeGduYS9z
            Lys4djNrK2xUWDRzcmlHc1R4dUY5R28KLS0tIGJJSEtQeEladUVJV242ajdvRENB
            bHozQmU1aTZML1ArQzVNMVRzTGxnWjAKTwtK7CIoBDs6MwrsAwrw6ydFm7FGkBYy
            ka6psHEWaW2uP9qY4QuYRaKn3s3eUcy/A/mzd5f6u1ygnKiMfQNt/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
    lastmodified: "2026-07-18T08:50:11Z"
    mac: ENC[AES256_GCM,data:BZ4AEP/UzY8DgIwdUZgIMNhpm4rsO5E8i3qxd2QP0zz6isztmQ8I+cWYZNd17n0/ACieeyUbtt5Il7PJrZ9ee9zZTiVHsZmETsRR3Phf/YiIw4K6XB+MtNoYoWP14+t8A6/QgNXq6QkjSBlwoOwo/7HNc6CZ66NDmTZP7z7Oro8=,iv:e2S0ItDGOsjS8YFuz1QrDfiJhqe75Q0gEJ7FUbLFQtc=,tag:AEu7B+pRAuTJ0Wu6QWxERA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type|name|namespace|labels|annotations)$
    version: 3.13.0
