vaultwarden:
  smtp:
    username:
      value: ENC[AES256_GCM,data:vhyJq5mKiompSglKcuLbgEnBwPGp1A==,iv:x4cdilqkjVlp7ste7YhucztU09SI/HWtqmpv0iimJSI=,tag:bih4zllSsAwr60vbWynyBQ==,type:str]
    password:
      value: ENC[AES256_GCM,data:1091Df2RqjkQUL4pw2noSg==,iv:YpSCfAzWkGdA7xYWkLPUDmqPh5QHOhSHcs3ayesp66w=,tag:NFM7vnyd3lB3OoG7e+PCHg==,type:str]
  adminToken:
    value: ENC[AES256_GCM,data:z4VrJV94fygeIHjZIMGE7ThrITVYRhDFuUHsHxLSEmPedapKwniSXowm0OYA1rKXZtKPaOm7nVf5zEmk7vI4wQ==,iv:FNouH7Oxjd5WsTJV8VwUI+V9jN5kxIhfW92TVNnxmpc=,tag:YtDI7eTr/Jhi2LW0GcvBDw==,type:str]
database:
  DATABASE_URL: ENC[AES256_GCM,data:Z2r3otJKOVxAO9PtGU1FJrClDV5e/YrTMVJ0CpzTDVg175PsAEtSGBbHui6Fg2wHtQBMa71SGu/vCQGQUUSkxZwsBMAnUxrNUSyxewFRn01ei0NkQjSj0PNgyaiXtRdV2g==,iv:zAmsFs7676EjrFh7kwvRU0rpXYjuf46o0mRlF8B2b8w=,tag:EJ4fdVoGP03anAUh68Oimw==,type:str]
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ3VrTTVhV2xoU0pvemZJ
      cmN5OFB1UHdVaGJlQjVSdmRBTitmWlJHL0JZCmJYNzZiZnlEWmx3emhQY2Fhcms2
      TnFEOGFJNTJYWit5RU5DdG5ET1RmUW8KLS0tIGhzYmJzQ2F3djVaK3V3OVk1Z0Ez
      VFlyelJDZ3IyMlBQUktTY1NqTmZudG8KgnG2mnObHo/bzxmwbs1cbQHSN05bHKB8
      u2L7zXnhmU2/+5i9MZ0h5Gjnn9PGQJwmkiicfNFX/sDTKmQY0t00KA==
      -----END AGE ENCRYPTED FILE-----
    recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
  lastmodified: "2026-07-18T09:17:11Z"
  mac: ENC[AES256_GCM,data:cB7AnzoAnWYSJxc84nsj4XPkUyjoWKaYKoQVVzDdnLhnK8c2mR4DS0nxTJCwXVV91v37YJnlHIAcYLDVMFKVaHvvXJvjg7l9bLx94U0HbfWrP0FSPRj0bqUtHRcwsyz/mBnFHp35sjviTvrJ08GwsfK25u/IHABZdtx6u9zmf7s=,iv:bQc/uuEpV/SCpJoPdl7vSouG7Te2AGmb4ABCia7NNVQ=,tag:6gUaOIsvq6X5RUR0/LF2JQ==,type:str]
  unencrypted_regex: ^(apiVersion|kind|metadata|type|name|namespace|labels|annotations)$
  version: 3.13.0
