apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pvc
  namespace: redis
  labels:
    app: redisinsight
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: juicefs-sc-cloudflare-r2
  resources:
    requests:
      storage: 2Gi
