#yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kafka.strimzi.io/kafkanodepool_v1.json
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role-pool
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  resources:
    requests:
      memory: 512Mi
      cpu: 300m
    limits:
      memory: 512Mi
      cpu: 1000m
  jvmOptions:
    -Xms: 256m
    -Xmx: 256m
    javaSystemProperties:
      - name: log4j2.formatMsgNoLookups
        value: "true"
    gcLoggingEnabled: false