apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kube-prometheus-stack-daily
  namespace: velero
spec:
  # 1. The Cron Expression: Runs at 1:00 AM every day
  schedule: "0 1 * * *"
  template:
    includedNamespaces:
    - kube-prometheus-stack
    excludedResources:
    - events.k8s.io
    - nodes
    storageLocation: r2-cloudflare
    defaultVolumesToFsBackup: true
    # (3 days)
    ttl: 72h0m0s
    snapshotVolumes: true
    includeClusterResources: null
