# https://cloudnative-pg.io/docs/1.30/cloudnative-pg.v1#database
{{- range $key, $val := .Values.cnpgDatabases }}
{{- $db := $val | default dict }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $key }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $db.syncWave | default $.Values.cnpgDefaults.syncWave | quote }}
spec:
  cluster:
    name: {{ $db.clusterName | default $.Values.cnpgDefaults.clusterName }}
  name: {{ $db.dbName | default $key }}
  owner: {{ $db.owner | default $key }}
---
{{- end }}