{{- range $key, $val := .Values.cnpgRoles }}
{{- $role := $val | default dict }}
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ $role.metaName | default (printf "postgresql-%s" ($key | replace "_" "-")) }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $role.syncWave | default $.Values.cnpgRoleDefaults.syncWave | quote }}
spec:
  cluster:
    name: {{ $role.clusterName | default $.Values.cnpgRoleDefaults.clusterName }}
  name: {{ $role.roleName | default $key }}
  {{- if $role.comment }}
  comment: {{ $role.comment | quote }}
  {{- end }}
  login: true
  superuser: false
  {{- if $role.connectionLimit }}
  connectionLimit: {{ $role.connectionLimit }}
  {{- end }}
  databaseRoleReclaimPolicy: {{ $role.reclaimPolicy | default $.Values.cnpgRoleDefaults.reclaimPolicy }}
  {{- if $role.inRoles }}
  inRoles:
    {{- range $role.inRoles }}
    - {{ . }}
    {{- end }}
  {{- end }}
  passwordSecret:
    name: {{ $role.passwordSecretName | default $key }}
{{- end }}