{{- range $key, $val := .Values.cnpgRoles }}
{{- $role := $val | default dict }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $role.passwordSecretName | default $key }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $role.syncWave | default $.Values.cnpgRoleDefaults.syncWave | quote }}
type: kubernetes.io/basic
stringData:
  username: {{ $role.roleName | default $key }}
  password: {{ $role.password | quote }}
{{- end }}