{{- if .Values.alloy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  labels:
    applicationType: daemon
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 5
  destination:
    namespace: alloy
    name: in-cluster
  syncPolicy:
    syncOptions: [ "CreateNamespace=true","ServerSideApply=true" ]
    automated:
      enabled: false
  source:
    repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/platform/alloy

{{- end }}