{{- if and (.Values.argus) (.Values.argus.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argus
  namespace: argocd
  labels:
    applicationType: stateless
spec:
  project: default
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argus
    name: in-cluster
  source:
    repoURL: https://github.com/ngodat0103/argus
    targetRevision: "master"
    path: deploy
{{- end }}
