{{- if and (.Values.jellyfin) (.Values.jellyfin.enabled) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
   namespace: jellyfin
   name: in-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      enabled: false
  source:
    directory:
      recurse: false
    repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/stateful/jellyfin
{{- end }}
