{{- if and (.Values.juicefs) (.Values.juicefs.enabled) -}}
apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: juicefs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  revisionHistoryLimit: 3
  project: default
  syncPolicy:
    automated:
      enabled: false
      selfHeal: false
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  destination:
    namespace: juicefs
    name: in-cluster
  sources:
    # https://artifacthub.io/packages/helm/wener/juicefs-csi-driver?modal=values
    - repoURL: https://charts.wener.tech
      chart: juicefs-csi-driver
      targetRevision: 0.31.4
      helm:
        values: |
          mountMode: mountpod
          metrics:
            enabled: true
            port: 9567
            service:
              servicePort: 9567
          globalConfig:
            mountPodPatch:
              - resources:
                  requests:
                    cpu: 200m
                    memory: 512Mi
                  limits:
                    cpu: 4
                    memory: 1Gi
          webhook:
            certManager:
              enabled: false
          controller:
            replicas: 1
          storageClasses:
            - name: "juicefs-sc-cloudflare-r2"
              enabled: true
              existingSecret: "cloudflare-r2"
              reclaimPolicy: Retain
              allowVolumeExpansion: true
              mountPod:
                resources:
                  requests:
                    cpu: 200m
                    memory: 512Mi
                  limits:
                    cpu: 4
                    memory: 2Gi
              mountOptions:
                - cache-size=10240
                - free-space-ratio=0.1
                - prefetch=3
                - max-readahead=67108864
                - open-cache=3
                - attr-cache=3
                - entry-cache=3
                - writeback
          dashboard:
            ingress:
              enabled: true
              className: "traefik"
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
                traefik.ingress.kubernetes.io/router.middlewares: "traefik-allow-local-ip-only@kubernetescrd"
                traefik.ingress.kubernetes.io/router.tls: "true"
                traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
              hosts:
                - host: "juicefs.datrollout.dev"
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
    # Raw manifests (ServiceMonitor, etc.) tracked in Git
    - repoURL: https://github.com/ngodat0103/dev-oops.git
      targetRevision: master
      path: kubernetes/argocd/argocd-app/daemon/juicefs
{{- end -}}