{{- if .Values.kubePrometheusStack.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: kube-prometheus-stack
    name: in-cluster
  syncPolicy:
    syncOptions: [ "CreateNamespace=true","ServerSideApply=true" ]
    automated:
      enabled: false
      prune: true
      selfHeal: true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 82.13.0
    chart: kube-prometheus-stack
    helm:
     ## https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack/82.13.0?modal=values
     values: |
      alertmanager:
        alertmanagerSpec:
          secrets:
            - alertmanager-smtp-credentials
        config:
          global:
            resolve_timeout: 5m
            smtp_smarthost: 'smtp.gmail.com:587'
            smtp_from: 'alertmanager@datrollout.dev'
            smtp_auth_username: '21521935@gm.uit.edu.vn'
            smtp_auth_password_file: '/etc/alertmanager/secrets/alertmanager-smtp-credentials/password'
            # smtp_require_tls: true
          route:
            group_by: ['namespace', 'alertname']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: 'to-me'
            routes:
              - matchers:
                  - alertname = "Watchdog"
                receiver: 'null'
          receivers:
            - name: 'null'
            - name: 'to-me'
              email_configs:
                - to: 'ngovuminhdat@gmail.com'
                  send_resolved: true
        ingress:
          enabled: true
          hosts: ["alert-manager.datrollout.dev"]
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-allow-local-ip-only@kubernetescrd"
      grafana:
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            searchNamespace: ALL
        admin:
          existingSecret: grafana-admin
          userKey: admin-user
          passwordKey: admin-password
        ingress:
          enabled: true
          hosts: ["grafana.datrollout.dev"]
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-allow-local-ip-only@kubernetescrd"
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
        additionalDataSources:
          - name: loki-in-cluster
            type: loki
            basicAuth: false
            editable: false
            jsonData:
                tlsSkipVerify: true
            orgId: 1
            url: http://loki.loki.svc.cluster.local:3100
            version: 1
      prometheus:
        prometheusSpec:
          podMonitorSelectorNilUsesHelmValues: false
          podMonitorNamespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: Exists   # matches ALL namespaces
          serviceMonitorSelectorNilUsesHelmValues: false
          serviceMonitorNamespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: Exists
          retention: 14d
          retentionSize: 15GiB
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 20Gi
{{- end }}