{{- if .Values.kubePrometheusStack.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    applicationType: stateless
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: kube-prometheus-stack
    name: in-cluster
  syncPolicy:
    syncOptions: [ "CreateNamespace=true","ServerSideApply=true" ]
    automated:
      enabled: false
  source:
    repoURL: https://github.com/ngodat0103/dev-oops.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/platform/kube-prometheus-stack
{{- end }}