{{- if .Values.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    applicationType: stateful
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: loki
    name: in-cluster
  syncPolicy:
    syncOptions: [ "CreateNamespace=true","ServerSideApply=true" ]
    automated:
      enabled: false
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ngodat0103/dev-oops.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/platform/loki
    # 
{{- end }}