{{- if .Values.metallb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    applicationType: platform
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: metallb
    name: in-cluster
  syncPolicy:
    syncOptions: [ "CreateNamespace=true" ]
    automated:
      enabled: false
      selfHeal: false
      prune: false
  source:
    repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/platform/metallb
{{- end }}
