{{- if .Values.openebs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: openebs
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  revisionHistoryLimit: 3
  project: default
  destination:
    name: in-cluster
    namespace: openebs
  syncPolicy:
    syncOptions: [ "ServerSideApply=true", "CreateNamespace=true" ]
    automated:
      enabled: false
      selfHeal: false
      prune: false
  sources:
  - repoURL: https://openebs.github.io/openebs
    chart: openebs
    targetRevision: 4.3.3
    helm:
     ## https://github.com/openebs/openebs/blob/v4.3.3/charts/values.yaml
     values: |
      loki:
        enabled: false
        minio:
          enabled: false
      alloy:
        enabled: false
      engines:
        local:
          lvm:
            enabled: false
          zfs:
            enabled: false
        replicated:
          mayastor:
            enabled: false
      mayastor:
        csi:
          node:
            initContainers:
              enabled: false
        etcd:
          # -- Kubernetes Cluster Domain
          clusterDomain: cluster.local
        localpv-provisioner:
          enabled: true
        crds:
          enabled: false
        loki:
          enabled: false
        alloy:
          enabled: false
      lvm-localpv:
        crds:
          lvmLocalPv:
            enabled: false
          csi:
            volumeSnapshots:
              enabled: false
      zfs-localpv:
        crds:
          zfsLocalPv:
            enabled: false
          csi:
            volumeSnapshots:
              enabled: false
      preUpgradeHook:
        enabled: false
{{- end }}