{{- if .Values.postgresql.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-postgresql
  namespace: argocd
  labels:
    applicationType: stateful
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    automated:
      enabled: false
      prune: false
      selfHeal: false
  destination:
    namespace: prod-postgresql
    name: in-cluster
  sources:
  - repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.28.2
    ## https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg/0.28.2?modal=values
    helm:
      values: |
        monitoring:
          grafanaDashboard:
            create: true
            namespace: kube-prometheus-stack
            labels:
              grafana_dashboard: "1"    
        metadata:
         annotations:
          argocd.argoproj.io/sync-wave: "0"
  - directory:
      recurse: true
    repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/stateful/postgresql/raw-manifests
  - repoURL: https://cloudnative-pg.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.7.0
{{- end }}
