{{- if and (.Values.sonarqube) (.Values.sonarqube.enabled) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 2026.2.0
    helm:
      # https://artifacthub.io/packages/helm/sonarqube/sonarqube/2026.2.0?modal=values
      values: |
        revisionHistoryLimit: 3
        deploymentType: Deployment
        monitoringPasscode: somePassCode
        resources:
          limits:
            cpu: 4000m
            memory: 6144M
            ephemeral-storage: 50Gi
          requests:
            cpu: 4000m
            memory: 6144M
            ephemeral-storage: 50Gi
        community:
          enabled: true
        persistence:
          enabled: false # not important. This just stores elastic cache; not a big deal.
          size: 30Gi
        jdbcOverwrite:
          enabled: true
          jdbcUrl: "jdbc:postgresql://postgresql-rw.prod-postgresql/sonarqube"
          jdbcUsername: sonarqube
          jdbcSecretName: sonarqube
          jdbcSecretPasswordKey: password
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-allow-local-ip-only@kubernetescrd"
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
          hosts:
          - name: sonarqube.datrollout.dev
        prometheusMonitoring:
          podMonitor:
            enabled: true
  destination:
    name: in-cluster
    namespace: sonarqube
  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}