{{- if .Values.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    applicationType: stateless
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  revisionHistoryLimit: 3
  destination:
    namespace: traefik
    name: in-cluster
  syncPolicy:
    syncOptions: [ "ServerSideApply=true", "CreateNamespace=true" ]
    automated:
      enabled: false
      selfHeal: true
      prune: true
  source:
    repoURL: https://github.com/ngodat0103/home-lab.git
    targetRevision: master
    path: kubernetes/argocd/argocd-app/platform/traefik
{{- end }}