apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  storageClassName: juicefs-sc-cloudflare-r2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
spec:
  storageClassName: ""
  volumeName: jellyfin-media-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1237Gi
