# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  affinity: {}
  # According to requirement of Gitlab
  # https://docs.gitlab.com/install/requirements/#postgresql-tuning
  resources:
    requests:
      memory: 1Gi
      cpu: "2000m"
    limits:
      cpu: "4000m"
      memory: 1Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-admin
  monitoring:
    enablePodMonitor: true
  bootstrap:
    recovery:
      source: origin
  externalClusters:
  - name: origin
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: cloudflare-r2
        serverName: postgresql
  # plugins:
  # - name: barman-cloud.cloudnative-pg.io
  #   isWALArchiver: true
  #   parameters:
  #     barmanObjectName: cloudflare-r2
  managed:
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: postgresql-externnal-rw
          spec:
            type: LoadBalancer
      - selectorType: ro
        serviceTemplate:
          metadata:
            name: postgresql-externnal-ro
          spec:
            type: LoadBalancer
    # roles:
    # - name: sonarqube
    #   ensure: present
    #   comment: Role for Sonarqube
    #   login: true
    #   superuser: false
    #   passwordSecret:
    #     name: sonarqube
    # - name: vaultwarden
    #   ensure: present
    #   comment: Role for Vaultwarden
    #   login: true
    #   superuser: false
    #   passwordSecret:
    #     name: vaultwarden
    # - name: gitlab
    #   ensure: present
    #   comment: "Role for Gitlab"
    #   login: true
    #   superuser: false
    #   passwordSecret:
    #     name: gitlab-db
    # - name: nextcloud
    #   comment: Role for nextcloud
    #   login: true
    #   superuser: false
    #   ensure: present
    #   passwordSecret:
    #     name: nextcloud-db
    # - name: pgadmin_monitor
    #   ensure: present
    #   login: true
    #   superuser: false
    #   passwordSecret:
    #     name: pgadmin-monitor-credentials
    #   inRoles:
    #   - pg_monitor
  instances: 2
  storage:
    size: 30Gi