# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  affinity: {}
  # According to requirement of Gitlab
  # https://docs.gitlab.com/install/requirements/#postgresql-tuning
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      cpu: "1"
      memory: 512Mi
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-admin
  monitoring:
    enablePodMonitor: true
  managed:
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: postgresql-externnal-rw
          spec:
            type: LoadBalancer
      - selectorType: ro
        serviceTemplate:
          metadata:
            name: postgresql-externnal-ro
          spec:
            type: LoadBalancer
    roles:
    - name: sonarqube
      ensure: present
      comment: Role for Sonarqube
      login: true
      superuser: false
      passwordSecret:
        name: sonarqube
    - name: vaultwarden
      ensure: present
      comment: Role for Vaultwarden
      login: true
      superuser: false
      passwordSecret:
        name: vaultwarden
    # - name: gitlab
    #   ensure: present
    #   comment: "Role for Gitlab"
    #   login: true
    #   superuser: false
    #   passwordSecret:
    #     name: gitlab-db
    # - name: nextcloud
    #   comment: Role for nextcloud
    #   login: true
    #   superuser: false
    #   ensure: present
    #   passwordSecret:
    #     name: nextcloud-db
    - name: pgadmin_monitor
      ensure: present
      login: true
      superuser: false
      passwordSecret:
        name: pgadmin-monitor-credentials
      inRoles:
      - pg_monitor
  instances: 3
  storage:
    size: 30Gi
    storageClass: "openebs-hostpath"
