apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-app-log-alerts
  labels:
    loki_rule: "true"
  annotations:
    loki_rule_folder: homelab
data:
  loki-app-log-alerts.yaml: |
{{ .Files.Get "files/loki-app-log-alerts.yaml" | indent 4 }}