secrets:
    cloudflareAPIToken: ENC[AES256_GCM,data:eTbHaqiwfLsCJ8+uOaIcvjQJ9ftrdlRuy1N1dFObgIBq1wKqNLWxpw==,iv:3vfK9gYabcfr5y+QpoUnGMudPZ0iyg106XvHUEQOeSY=,tag:RCLHiTi6WpRZjYOx2JcYjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUkdFTHZWNVFyT01JU1Ev
            N2V0UG1KR3kyZzMydTFaSXpsNDBsOXh2UzBrCjZqS0JmaVJmSTRaL0U1dk1Vc1Qx
            WGxrQjBCZ2h4SU42eUU5NStkc2Fham8KLS0tIDdGbFZ5ak9BVVo1eTNsTWZlRFQ1
            REhaaDZqVk5VR0ZLUi82THdkUFc3Nk0KThMYmZQtScgl2VLozMgaQbSQrMPLPg9a
            aC7ijp341yuZcKSGZ0Cp5FTPDNgWxUFWJlMT8mHHD7KfVqr1M7GwOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
    encrypted_regex: (?i)^(data|stringData)$|secret|password|passwd|pwd|token|api[-_]?key|access[-_]?key|private[-_]?key|secret[-_]?key|client[-_]?secret|credential|passphrase|connection[-_]?string|dsn|webhook|signing[-_]?key|encryption[-_]?key|cert(ificate)?
    lastmodified: "2026-08-09T05:05:42Z"
    mac: ENC[AES256_GCM,data:Ne4N3ijXDgI6XCdvtbl6EjQv0qcY6WOpW+sxZ6qnPhdvsSyzBhwdDJmlas2qQk1hVRLN7GESil/jB7O6EqgbeHwrOnV+YM92oWyIPbdY5qY4gou+KUwez8RflvGVpleRZIzhZ5BoD7YaNBeO246tDC/hUdhVXo4UZgoEQ22s96M=,iv:Timq2QI37jQjPGHpQItrS1lNKSfpIKaAImdhE5khyHg=,tag:ixVHqoYXiEz8ryJ1wCo+KA==,type:str]
    version: 3.13.0
