apiVersion: v1
kind: ConfigMap
metadata:
  name: disk-dashboard-proxmox
  labels:
    grafana_dashboard: "1"
data:
  disk-dashboard-proxmox.json: |-
{{ .Files.Get "files/disk_monitor_dashboard_10530_rev7.json" | nindent 3}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: disk-proxmox-alerts
  labels:
    release: kube-prometheus-stack
spec:
{{ .Files.Get "files/disk-proxmox-alert.yaml" | indent 2 }}