cnpgRoles:
  sonarqube:
    password: ENC[AES256_GCM,data:I5SOAyFxE6acyKVngww=,iv:XOzLRsCzMi+UM9clf3wLf76QSbnEomc0F9/Wc8AnYPg=,tag:WyqKaT9DsRXhjSxpto63LQ==,type:str]
  vaultwarden:
    password: ENC[AES256_GCM,data:/tWdOFeaL8HFzY+ZEOVr/vEAQq93c+S8Uc86yEtP,iv:aEt+D50dlTNf1ZXQ7lfleLnRXIz37OpCAj95jIXm464=,tag:5G5S3oC3QfAQyDGL4cANpg==,type:str]
  gitlab:
    password: ENC[AES256_GCM,data:zLDUSBYYP9nU+4T+n0I=,iv:7NiaL3uhvPeoBIAXTSoldUXNOgUOTIuM722WyS1vf7I=,tag:2BI54KyPPRJDB8GsLoHRGw==,type:str]
  nextcloud:
    password: ENC[AES256_GCM,data:WYFAcXuHAjLkXbg9RSg=,iv:xsxli5P+GBBQDxIBVB0TTdjog80LgXWvf7Cf7eTH//o=,tag:dRp2dry3WOaMsU9mAhzdoQ==,type:str]
  juicefs:
    password: ENC[AES256_GCM,data:5LF9cnWXo8YIXcvR3R85Hvd3AHA=,iv:7k4GDhaUAZSwLY53Zde7heWnLFziDPs17I4671vMT4w=,tag:pJLnhppHEwiOUQFQGI6M3w==,type:str]
  argus:
    password: ENC[AES256_GCM,data:pE9qB4OlY+kK6mobekk=,iv:Vn+vkdtgfL9qHAKxfSUHP0A2+JI5HzRDlgzTHmkGvc4=,tag:OzzP50TEGTKrPqpFgZRAqg==,type:str]
  crowsec:
    password: ENC[AES256_GCM,data:BeEhIwydrkOOygFAggE=,iv:dhtuNmcQdKeP0eHaucwQq1dyCmfnkR5NWjau61Kp+p4=,tag:j8hH/Zkssdg4AW7mh4fZ7A==,type:str]
  teleport:
    password: ENC[AES256_GCM,data:/9CAn11TtP5DOF0Cai8=,iv:qvzzt/Zlo6jZAafKCjvHvmbe7fo9d17Ye6g6kijsbJU=,tag:8cQxtqafQAsPwKPOIMz4pg==,type:str]
  pgadmin_monitor:
    password: ""
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTVY5NUJ6NlZUVnFjVEQx
      NVlwOW03bE1pcW5KejFGMDZ5Q0Q0MTl3OEgwCktlUWkzVG92cW4xRy8wb0Z1WUUw
      M204UzhHQmhyZXltYlB0cUZlUlRPTlUKLS0tIG0xN2xQc3RoK1A4VlovZnB3Z2NE
      NmtUM0lqN1QrTWNIaGwvQ0liR1JwSXcK5WbSKQxmIRFlTZ8t9gtv3LJfIXpWK/qZ
      ZtaJl/h9ugEoASsAAGqC3Jihcv896pFvHOpL57cUKzSlk0e8QTHg6g==
      -----END AGE ENCRYPTED FILE-----
    recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
  encrypted_regex: (?i)^(data|stringData)$|secret|password|passwd|pwd|token|api[-_]?key|access[-_]?key|private[-_]?key|secret[-_]?key|client[-_]?secret|credential|passphrase|connection[-_]?string|dsn|webhook|signing[-_]?key|encryption[-_]?key|cert(ificate)?
  lastmodified: "2026-08-08T05:01:39Z"
  mac: ENC[AES256_GCM,data:chOhXFoVbV8VfvLAnCT0r0G6O/xMcNje2C82vLXxH5ZE/4bevWQnEtj5r0JUtBzJo+owZFxnrRhs9mQvNvwcte7EKvaNC6bdACiM4MduzuBNA+CgxGsA8jNe07geANmsJG4nakkCWJxt3JLavR+HiKMZAKIZWdRQysbsviXqVes=,iv:L6zg+3JU3u4yMg97ovjyyoX5jC7Krh1bq7Mk3GPL3zU=,tag:LR0zz8W3p6GJ41WKofabIw==,type:str]
  version: 3.13.0
