apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: juicefs-csi-driver
  namespace: juicefs
spec:
  namespaceSelector:
    matchNames:
      - juicefs
  selector:
    matchLabels:
      app.kubernetes.io/name: juicefs-csi-driver
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
