secrets:
    #ENC[AES256_GCM,data:TvwW1m+0R6l+PTMVl6yDLYOzvUR+vDyZfYnygZPISlQ7nX+l7oYtvnLnpmQ=,iv:KH/vSRfL5gsxMnWmIAw+WAZ1Qejupq58W3V51PaB0eE=,tag:QFFteon/uRz+kZhLGRJ2Ew==,type:comment]
    db-password: ENC[AES256_GCM,data:S2hZuElo7ZChxJJ6RGs=,iv:9VP21TgQOV3g4m6BMMBRdT1pDyNdIs56bOBFpUl2D3k=,tag:XBMnLh18EN5gcDd7b9xw5w==,type:str]
    pg-pass: ENC[AES256_GCM,data:e/Luz5M/rlRSqZvMLgd3tQ70l+O2WAsXgWe0UlrDn8i2j36/yrxUZrHTmZkzDQ4169FT47X/QfR42hJHf2F9ibtB5C4JKKsGGKEwq6Mgpjk5BA7aZ+W2ql+LsXQr7BZ+PLRSGuYJqr6uGSYhLo/IeDCCdkzYKVtU0pcpusEqouxSjYQX/MC8XrigAeGu997KuGWvkx74rVd+9zgyEg==,iv:UM5UOxS/D0pv1gTKtNjgIWTRwBntsvmD3loEHyuso1M=,tag:h+vCqftw2Rc3Hi0jqVjIng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dE5KVG00eFRYcFJpY3Jn
            aUJNakx4SUN3dGVpb3JBRS9uVGh1ekE0YlVFClFVMENUVGF5R21uYWVtTmNud3pY
            UldSN1JDeC96Njc4aDl2c3dteXozdFUKLS0tIEs3bmJNNm9IUnViLzNCTXBiaDJC
            a3lWSS85Y0Y5Mm5penoxQkpvT05XV1UKM+gxQe9mnPOw9CcLYbkF5JvmE6mr+aiw
            MY5pP5TaiLGRvRRUOPA7d86Oh1+qKApJGfG5r9H37x/cZyqSo6ve6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
    encrypted_regex: (?i)^(data|stringData)$|secret|password|passwd|pwd|token|api[-_]?key|access[-_]?key|private[-_]?key|secret[-_]?key|client[-_]?secret|credential|passphrase|connection[-_]?string|dsn|webhook|signing[-_]?key|encryption[-_]?key|cert(ificate)?
    lastmodified: "2026-08-08T09:31:36Z"
    mac: ENC[AES256_GCM,data:u889jL39c8+VF6x/ePdVVvqBFegom+R7lx4dLLwE8qPv5QD4qpbXFehZRDbCxIP1KHwipJ7x2GEll1WKM9f29EgeF6sq9r6Ia45rFA4RputsEmE0vbdDF1qDs4xJJuBXHo6dRHxdCBf30Vjbts1Uadpuc7ECZ+1m8dXOpPBsNy0=,iv:uArBgxNReRBmqmD7XqBeK5FMz5kY4QzBGJgdNpoYxNk=,tag:t1vB1s028m4Y9xlHDzm7fA==,type:str]
    version: 3.13.0
