## https://artifacthub.io/packages/helm/argo/argo-cd/9.5.14?modal=values
dex:
  enabled: false
notifications:
  enabled: false
redis:
  resources:
    requests:
      cpu: 500m
      memory: 64Mi
    limits:
      cpu: 1
      memory: 128Mi
controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
repoServer:
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi
server:
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 1
      memory: 256Mi
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    # -- Specific implementation for ingress controller. One of `generic`, `aws` or `gke`
    ## Additional configuration might be required in related configuration sections
    controller: generic
    # -- Additional ingress labels
    labels: {}
    # -- Additional ingress annotations
    ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-allow-local-ip-only@kubernetescrd"
global:
  domain: argocd.datrollout.dev
configs:
  params:
    server.insecure: true
  tls:
    create: true
crds:
  # -- Install and upgrade CRDs
  install: true
  # -- Keep CRDs on chart uninstall
  keep: false
