apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  annotations:
   argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
 api-token: {{ .Values.secrets.cloudflareAPIToken |b64enc| quote }}