secrets:
    - name: ENC[AES256_GCM,data:8Ud8KkKkBcr2uYahqg==,iv:mM9i1h2SkjUilFMmiKfkp/gEM7hUt6VB85YmGIrvY5o=,tag:s8Dp8oYbPzFTSC/HWcw9WQ==,type:str]
      stringData:
        name: ENC[AES256_GCM,data:dTvZlIjQZ3yOiYgbORjAnVc0,iv:ZXLXFH+rii2fqgMZ7b31e9sWM97nX9L7ebRGExxmjTs=,tag:Ly/1zONyz/ZCLhmzGKpKhg==,type:str]
        metaurl: ENC[AES256_GCM,data:qEkpIznpT3zVJkX2ED3PkcrYgfK5ypyCYuD36gT0kvhVVrJbwfhJuU+zZlNCUSgsvYEwIjr06nAD8fWhFJFKegHYcc97cMzu7bfxCVs=,iv:5BtKLrEiTVK43iuL02P7WSZj6wREOEB7vep20aMtlAs=,tag:2Ry+5SECpHw1LRCoqhxFmQ==,type:str]
        storage: ENC[AES256_GCM,data:ku8=,iv:EUxavxsr7ShqXTuu3sSm70nyJ11es9073RBfdCPpl9w=,tag:a+v5IggSVvwdOInIU/XHwA==,type:str]
        bucket: ENC[AES256_GCM,data:KBxsWw0kDhSRF5Zc6WlTZc/u+0j1Jat9qX2RHi0p8qb3NaRdBLSmQdgUrpD6Ukm1HymhsnD1QKiauO/3BsVxZ8cKtXRSOKVjdm6PujIs,iv:CSLNmvIB81RPvf2nPrKc4h6cjtVmZk3+Fgxe0H8QmH0=,tag:iyD5XpzCbbS73JG1xU46lQ==,type:str]
        accessKey: ENC[AES256_GCM,data:Xd+UQuMOeN2Fpi6eBSMIAVrs2YEWlD/N/boJJMoAZ5s=,iv:tXcYspVaFSODkKs1s3FmEvImlz2P8jd+H/QQy5+T+aE=,tag:6ZdelDbSLhuBd/xS7b4HwA==,type:str]
        secretKey: ENC[AES256_GCM,data:enD2GJUzlxDEhK7dlhTyCD+BFfDEVri7CLTHEK2d6+3g/y/euETgA1dkqRuZACWZahZajpZtBrtgF8X1Moq4tw==,iv:NHk/QiA9BbWK6v6lGj1I3KUuvBhZRAyqIvgwzK8pAaI=,tag:FuNBGuxppIOnqkBdjByFUQ==,type:str]
        #ENC[AES256_GCM,data:53/9U+SQYhrewNAIGaBiVyCZ7rUfAEzGgoWAnVkaqqhgtug+3f3mmhV7i4yx6yU7k5evm/ol3g==,iv:lLJf75lKQl1w+XEBJ9Fttov4sJ9+Ne2p9ykJq6Z7x+U=,tag:GyITnd193+1Vn63QQhhM0w==,type:comment]
        #ENC[AES256_GCM,data:WFpb0xgyUCnfMaKWqzkCsvBSC6CwwYFz91BDQ0eGgBMK+kgcP5FgTfYnuMhLUQgz2w==,iv:V4LPZNSNPmk/iev+2v0kdIdNf4a8IwFwWB2m2XZUJVs=,tag:aOYXlb9x2GUK4NeB9IsGbw==,type:comment]
        envs: ENC[AES256_GCM,data:wZijky8lF2IQl+Cj5lqR6upWmJZklzBh,iv:zaN+9BovFRtRcX5N2/O+OTdgt6qO2l7+K2n888LkoyY=,tag:KgEvFCj65XYHq+rFg5cYJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVU9YSEltR0gxSi9wN0hz
            eWdOMHloV1dmY1Nxa2tGZlI5REQvcjJWejE0CmhJYUJKbmFZa2hUU1FGSTZudHh4
            NUw5VnpaZFlPVFc0SzljNUxxVms3S0kKLS0tIFJVK2tlendNbXRTcStDVjQ2T05V
            alpGa1RIWVFVV3RranNxRDNKejQyZ0UKDfXCbySyENkgGAXHZM+0pevxXJTPpxka
            gqTtUIcQgnyrZVKFa+lRpPScDKkyWDesBCikY5uFKiX8eopia34jZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fuj3pug8qvqe3mlls0qjgysepn68gmqpcdk8dpsmpl7tq3fqydhqpu9p7p
    encrypted_regex: (?i)^(data|stringData)$|secret|password|passwd|pwd|token|api[-_]?key|access[-_]?key|private[-_]?key|secret[-_]?key|client[-_]?secret|credential|passphrase|connection[-_]?string|dsn|webhook|signing[-_]?key|encryption[-_]?key|cert(ificate)?
    lastmodified: "2026-08-02T05:48:01Z"
    mac: ENC[AES256_GCM,data:dsuvrDcud3mKcsqBgu1M5UZy2pgqsLsuUNlJM2CUEarh3k/Ma9iMiqaBCeDj7veoaUD6YOHi8NqKKQbkpVVe5cJ2xpscuUj4zYRNoJ891P/P6axMoJQuFzOS5/+JJTzVqtXpf0d5im4Jo7OWHaQrMsPnlg/ok0UHO57u0DxbGfE=,iv:nBfKhBrqj/d/j+YAI88fSv8VkUYwM5YA4cyZXUfPLoM=,tag:XDaBWwiXGVmf4b3xQ7lsOg==,type:str]
    version: 3.13.0
