- name: Manage Alloy instance (native service)
  hosts: ubuntu-server
  become: yes
  vars:
    uid: 473
    config_path: /etc/alloy/

  tasks:
  - name: Create alloy user
    ansible.builtin.user:
      name: alloy
      uid: "{{ uid }}"
      groups: ["adm", "systemd-journal"]
      system: yes
      shell: /usr/sbin/nologin

  - name: Add Grafana GPG key
    ansible.builtin.get_url:
      url: https://apt.grafana.com/gpg.key
      dest: /usr/share/keyrings/grafana.key
      mode: "0644"

  - name: Add Grafana APT repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com/ stable main"
      filename: apt_grafana_com
      state: present

  - name: Install Alloy package
    ansible.builtin.apt:
      name: alloy
      state: present
      update_cache: yes

  - name: Make sure config directory exists
    ansible.builtin.file:
      dest: "{{ config_path }}"
      owner: "{{ uid }}"
      group: alloy
      mode: "0750"
      state: directory

  - name: Copy Alloy config to remote machine
    ansible.builtin.copy:
      src: config.alloy
      dest: "{{ config_path }}"
      mode: "0600"
      owner: "{{ uid }}"
      group: alloy
    notify: restart alloy

  - name: Ensure Alloy service is enabled and running
    ansible.builtin.systemd:
      name: alloy
      enabled: yes
      state: started

  handlers:
  - name: restart alloy
    ansible.builtin.systemd:
      name: alloy
      state: restarted