apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app-pvc
  namespace: nextcloud
spec:
  storageClassName: juicefs-sc-cloudflare-r2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 105Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mnt-pvc
  namespace: nextcloud
spec:
  storageClassName: ""
  volumeName: nextcloud-mnt-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
